# Application
spring.application.name=gym-class-booking-api
server.port=${PORT:8080}

# Datasource
spring.datasource.url=jdbc:h2:mem:gymDB
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=sa

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.defer-datasource-initialization=true

# SQL Initialization
spring.sql.init.mode=always

# H2 Console
spring.h2.console.enabled=${H2_CONSOLE_ENABLED:true}
spring.h2.console.path=/h2-console

# Logging Configuration
logging.level.root=INFO
logging.level.se.edugrade.java25.enterprise.gym=DEBUG

# Swagger / SpringDoc
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

# JWT
jwt.secret=${JWT_SECRET}